### ISSUE TITLE
Success method called twice

### ISSUE THREAD

**Issue by buildsomethingdifferent** [redsd/vue-apple-signin#1]
Whenever I get response from apple and my onSuccess function is called twice. This behavior is strange I have debugged my code and didnt find anything where Im calling success method Twice.

**Comment by redsd** [comment]
It could be that Apple fires an event called 'AppleIDSignInOnSuccess' multiple times, or the apple login button is added multiple times to you application. Everytime the button is added an listener is set to the document property to listen for incoming calls from Apple, unfortunaly we can't distinct it from which button that is clicked.

**Comment by neilobremski** [comment]
I ran into `AppleIDSignInOnSuccess` being called multiple times today and finally figured it out: if you load Apple's Javascript file more than once then it duplicates whatever code is going to dispatch this event and thereby you get called twice, three times, or however many times you've loaded the script.

I was dynamically loading the script by creating a `script` DOM element and setting `src` and it caused this to happen. It was driving me absolutely batty because Google's JS Sign In code doesn't have this side effect.
