### ISSUE TITLE
Styling not working properly

### ISSUE THREAD

**Issue by eakenbor** [redsd/vue-apple-signin#4]
I applied the styling and props as shown below but the logo and the text are appearing on different lines instead of the same line. The logoPosition and labelPosition are not having any effect at all. Using mode as center-align makes it impossible to change the size and location of the logo and text.

Please can anyone help?

![Inspectorama - 2023-03-23T211639 220](https://user-images.githubusercontent.com/30095266/227342396-ec824cc1-3bb3-4ec0-a1c4-167a2a691d80.png)

````
 <vue-apple-login
        mode="left-align"
        type="sign in"
        color="white"
        :border="false"
        :radius="5"
        width="100%"
        height="35"
        logoSize="medium"
        logoPosition="0"
        labelPosition="0"
        className="
                  btn
                  line-height-20
                  font-weight-400
                  border-color-grey
                "
        :onSuccess="onAppleSignInSuccess"
        :onFailure="
          (error) => {
            console.log(error);
          }
        "
      ></vue-apple-login>````

**Comment by redsd** [comment]
it looks like a css class is interfering with the apple styling that is applied.
When you inspect the apple sign in button with the element inspector you should see probally multiple styling sources applied.

Because the button is generator with Apple's generator I have no control over the css.
The only thing you can do is fix your templates css so it doesn't break the Apple login button.
